# Generated by Django 6.0.5 on 2026-06-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_prompt_link',
            field=models.TextField(blank=True, null=True, verbose_name='AI Prompt Link'),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AI Source'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_websites',
            field=models.TextField(blank=True, null=True, verbose_name='Related Websites'),
        ),
    ]
